application: causal-destiny-157016
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js

- url: /css/(.*\.(css))
  static_files: css/\1
  upload: css/(.*\.(css))

- url: /.*
  script: templates.app

libraries:
- name: jinja2
  version: latest
